PROJECT_ROOT=/home/nikhil/Javaworkspace/RestSimpleAppMaven/
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/activation-1.1.1.jar -DgroupId=org.nikhil.activation -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/asm-3.3.1.jar -DgroupId=org.nikhil.asm -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/azure-bing-search-java-0.12.0.jar -DgroupId=net.billylieurance.azuresearch -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/commons-codec-1.6.jar -DgroupId=org.nikhil.commonscodec -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/commons-logging-1.1.1.jar -DgroupId=org.nikhil.commonslogging -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/fluent-hc-4.2.3.jar -DgroupId=org.nikhil.fluent -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/gson-2.2.2.jar -DgroupId=org.nikhil.gson -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/httpclient-4.2.3.jar -DgroupId=org.nikhil.httpclient -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/httpclient-cache-4.2.3.jar -DgroupId=org.nikhil.httpclientcache -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/httpcore-4.2.2.jar -DgroupId=org.nikhil.httpcore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/httpmime-4.2.3.jar -DgroupId=org.nikhil.httpmime -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jackson-core-asl-1.9.2.jar -DgroupId=org.nikhil.jacksoncore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jackson-jaxrs-1.9.2.jar -DgroupId=org.nikhil.jacksonjaxrs -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jackson-mapper-asl-1.9.2.jar -DgroupId=org.nikhil.jacksonmapper -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jackson-xc-1.9.2.jar -DgroupId=org.nikhil.jacksonxc -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jaxb-api-2.2.4.jar -DgroupId=org.nikhil.jaxbapi -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jaxb-impl-2.2.4-1.jar -DgroupId=org.nikhil.jaxbimpl -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jersey-client-1.17.jar -DgroupId=org.nikhil.jerseyclient -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jersey-core-1.17.jar -DgroupId=org.nikhil.jerseycore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jersey-json-1.17.jar -DgroupId=org.nikhil.jerseyjson -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jersey-server-1.17.jar -DgroupId=org.nikhil.jerseyserver -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jersey-servlet-1.13.jar -DgroupId=org.nikhil.jerseyservlet -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jettison-1.1.jar -DgroupId=org.nikhil.jettison -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/jsr311-api-1.1.1.jar -DgroupId=org.nikhil.jsr -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/stax-api-1.0-2.jar -DgroupId=org.nikhil.stax -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/twitter4j-async-3.0.3.jar -DgroupId=org.nikhil.twitter4j.async -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/twitter4j-core-3.0.3.jar -DgroupId=org.nikhil.twitter4j.core -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/twitter4j-examples-3.0.3.jar -DgroupId=org.nikhil.twitter4j.examples -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/twitter4j-media-support-3.0.3.jar -DgroupId=org.nikhil.twitter4j.media -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/twitter4j-stream-3.0.3.jar -DgroupId=org.nikhil.twitter4j.stream -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$PROJECT_ROOT/WebContent/WEB-INF/lib/wstx-asl-2.0.2.jar -DgroupId=org.nikhil.wstx -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
