vspath=`pwd`
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/activation-1.1.1.jar -DgroupId=org.nirbhaya.verticalsearch.activation -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/asm-3.3.1.jar -DgroupId=org.nirbhaya.verticalsearch.asm -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/azure-bing-search-java-0.12.0.jar -DgroupId=net.billylieurance.azuresearch -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/commons-codec-1.6.jar -DgroupId=org.nirbhaya.verticalsearch.commonscodec -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/commons-logging-1.1.1.jar -DgroupId=org.nirbhaya.verticalsearch.commonslogging -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/fluent-hc-4.2.3.jar -DgroupId=org.nirbhaya.verticalsearch.fluent -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/gson-2.2.2.jar -DgroupId=org.nirbhaya.verticalsearch.gson -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpclient-4.2.3.jar -DgroupId=org.nirbhaya.verticalsearch.httpclient -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpclient-cache-4.2.3.jar -DgroupId=org.nirbhaya.verticalsearch.httpclientcache -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpcore-4.2.2.jar -DgroupId=org.nirbhaya.verticalsearch.httpcore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpmime-4.2.3.jar -DgroupId=org.nirbhaya.verticalsearch.httpmime -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-core-asl-1.9.2.jar -DgroupId=org.nirbhaya.verticalsearch.jacksoncore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-jaxrs-1.9.2.jar -DgroupId=org.nirbhaya.verticalsearch.jacksonjaxrs -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-mapper-asl-1.9.2.jar -DgroupId=org.nirbhaya.verticalsearch.jacksonmapper -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-xc-1.9.2.jar -DgroupId=org.nirbhaya.verticalsearch.jacksonxc -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jaxb-api-2.2.4.jar -DgroupId=org.nirbhaya.verticalsearch.jaxbapi -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jaxb-impl-2.2.4-1.jar -DgroupId=org.nirbhaya.verticalsearch.jaxbimpl -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-client-1.17.jar -DgroupId=org.nirbhaya.verticalsearch.jerseyclient -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-core-1.17.jar -DgroupId=org.nirbhaya.verticalsearch.jerseycore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-json-1.17.jar -DgroupId=org.nirbhaya.verticalsearch.jerseyjson -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-server-1.17.jar -DgroupId=org.nirbhaya.verticalsearch.jerseyserver -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-servlet-1.13.jar -DgroupId=org.nirbhaya.verticalsearch.jerseyservlet -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jettison-1.1.jar -DgroupId=org.nirbhaya.verticalsearch.jettison -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jsr311-api-1.1.1.jar -DgroupId=org.nirbhaya.verticalsearch.jsr -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/stax-api-1.0-2.jar -DgroupId=org.nirbhaya.verticalsearch.stax -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-async-3.0.3.jar -DgroupId=org.nirbhaya.verticalsearch.twitter4j.async -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-core-3.0.3.jar -DgroupId=org.nirbhaya.verticalsearch.twitter4j.core -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-examples-3.0.3.jar -DgroupId=org.nirbhaya.verticalsearch.twitter4j.examples -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-media-support-3.0.3.jar -DgroupId=org.nirbhaya.verticalsearch.twitter4j.media -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-stream-3.0.3.jar -DgroupId=org.nirbhaya.verticalsearch.twitter4j.stream -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/wstx-asl-2.0.2.jar -DgroupId=org.nirbhaya.verticalsearch.wstx -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/mongo-2.10.1.jar -DgroupId=org.nirbhaya.verticalsearch.mongo -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
