$(document).ready(function(){
    $('#locationimg').click(function(e){
        $('#overlay').fadeIn('slow',function(e){
            $('#maphider').slideDown("slow");
            $('#someframe').attr('src','map5.html');
        });
        e.preventDefault();
    });
    $('.mapboxclose').click(function(){
        $('#maphider').slideUp('slow',function(){
            $('#overlay').fadeOut("slow");
        });
    });
});
