vspath=/home/sandeep/workspace/Trending
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/activation-1.1.1.jar -DgroupId=org.nirbhaya.trending.activation -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/asm-3.3.1.jar -DgroupId=org.nirbhaya.trending.asm -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/azure-bing-search-java-0.12.0.jar -DgroupId=net.billylieurance.azuresearch -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/commons-codec-1.6.jar -DgroupId=org.nirbhaya.trending.commonscodec -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/commons-logging-1.1.1.jar -DgroupId=org.nirbhaya.trending.commonslogging -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/fluent-hc-4.2.3.jar -DgroupId=org.nirbhaya.trending.fluent -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/gson-2.2.2.jar -DgroupId=org.nirbhaya.trending.gson -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpclient-4.2.3.jar -DgroupId=org.nirbhaya.trending.httpclient -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpclient-cache-4.2.3.jar -DgroupId=org.nirbhaya.trending.httpclientcache -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpcore-4.2.2.jar -DgroupId=org.nirbhaya.trending.httpcore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/httpmime-4.2.3.jar -DgroupId=org.nirbhaya.trending.httpmime -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-core-asl-1.9.2.jar -DgroupId=org.nirbhaya.trending.jacksoncore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-jaxrs-1.9.2.jar -DgroupId=org.nirbhaya.trending.jacksonjaxrs -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-mapper-asl-1.9.2.jar -DgroupId=org.nirbhaya.trending.jacksonmapper -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jackson-xc-1.9.2.jar -DgroupId=org.nirbhaya.trending.jacksonxc -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jaxb-api-2.2.4.jar -DgroupId=org.nirbhaya.trending.jaxbapi -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jaxb-impl-2.2.4-1.jar -DgroupId=org.nirbhaya.trending.jaxbimpl -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-client-1.17.jar -DgroupId=org.nirbhaya.trending.jerseyclient -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-core-1.17.jar -DgroupId=org.nirbhaya.trending.jerseycore -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-json-1.17.jar -DgroupId=org.nirbhaya.trending.jerseyjson -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-server-1.17.jar -DgroupId=org.nirbhaya.trending.jerseyserver -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jersey-servlet-1.13.jar -DgroupId=org.nirbhaya.trending.jerseyservlet -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jettison-1.1.jar -DgroupId=org.nirbhaya.trending.jettison -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/jsr311-api-1.1.1.jar -DgroupId=org.nirbhaya.trending.jsr -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/stax-api-1.0-2.jar -DgroupId=org.nirbhaya.trending.stax -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-async-3.0.3.jar -DgroupId=org.nirbhaya.trending.twitter4j.async -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-core-3.0.3.jar -DgroupId=org.nirbhaya.trending.twitter4j.core -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-examples-3.0.3.jar -DgroupId=org.nirbhaya.trending.twitter4j.examples -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-media-support-3.0.3.jar -DgroupId=org.nirbhaya.trending.twitter4j.media -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/twitter4j-stream-3.0.3.jar -DgroupId=org.nirbhaya.trending.twitter4j.stream -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
mvn install:install-file -Dfile=$vspath/WebContent/WEB-INF/lib/wstx-asl-2.0.2.jar -DgroupId=org.nirbhaya.trending.wstx -DartifactId=1.0 -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
